name: publish
permissions: write-all
on: [push]
jobs:
  publish-python3-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build the python3 Docker image
        run: |
              docker build . --tag ghcr.io/rafaelperazzo/python3:latest
              docker run ghcr.io/rafaelperazzo/python3:latest
              docker push ghcr.io/rafaelperazzo/python3:latest